### ISSUE TITLE
Does it support async / sync calls ?

### ISSUE THREAD

**Issue by solisoft** [taojy123/valval#10]
Hi, 

I'm using ArangoDB and they have a HTTP Rest API to deal with. I'm also currently using Lua / openresty for my code. Lua has a nice feature called `coroutine` which allow you to write your code as simply as : 

```lua
-- do anything here
http.simple({ url = url,  method = method, body = body, headers = headers })
-- do anything here
```

The code will not be a blocking code and the http response will be handled when the service respond.

Can we do that within VLang ?

**Comment by taojy123** [comment]
Sorry for the late reply.
vlang does not currently support the async approach to concurrency.
The official documentation says this
```
V's model of concurrency is very similar to Go's. To run foo() concurrently, just call it with go foo(). Right now, it launches the function on a new system thread. Soon coroutines and a scheduler will be implemented.
```
so, the `go` command just implemented by system thread，not a real coroutine.

**Comment by solisoft** [comment]
Thanks for the answer ... I read it too ... and you can't get value from it ! So I'll need next version I think
