### ISSUE TITLE
Vue v- directives

### ISSUE THREAD

**Issue by goldcoders** [taojy123/valval#11]
Templating engine uses by valval has same syntax as vue...
is there a way to override the v-  syntax to e.g. x-, coz i u use vue also in the template
that would be capture by valval templating engine instead of vue rendering it...

**Comment by taojy123** [comment]
Sorry, valval's template engine is vue, which conflicts with the vue you're using. 😂
I would try to fix this, e.g. customize whether to use the vue template engine or not.
Or I would suggest that you can separate the front and back side, valval only provides api, and the front side uses vue for static pages.
