### ISSUE TITLE
lots of errors in newer version

### ISSUE THREAD

**Issue by DavidSatimeWallin** [taojy123/valval#12]
I'm on version 0.1.29 of V and I'm getting lots of errors when trying to use valval.
Is there any progress on upgrading it to support a later version? Otherwise I'll give it a shot and might throw up a PR for it. Just wanna check first so I'm not doing work someone else already started.

**Comment by taojy123** [comment]
Hi! When I first developed valval, vlang was version `0.1.24`, and later I found that there were many problems with `0.1.25`. Many reasons made me plan to drop support for all versions before  `1.0`.
My time and abilities are limited, and I hope more people like you will join us, and together we can make valval and vlang better.

**Comment by taojy123** [comment]
I have transferred the valval project to the valvalio organization.
I hope that more people will come together to develop and maintain this project, and that the V language will be better.
