### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by v4violet** [taojy123/valval#13]
The claim "Valval is the fastest web framework in V language." is a bit weird to say if there aren't any benchmarks to show for?

**Comment by taojy123** [comment]
Hi, it's repeated with the previous https://github.com/valvalio/valval/issues/3 
Just a slogan, don't take it too seriously. And it means people can **develop a website more faster** , because it's so easy.
☺

**Comment by DavidSatimeWallin** [comment]
That slogal should probably be changed to something like "Valval aims to be the fastest web framework in V language - when developing and in production". As you point out @TurboBiscuit it can not be proven right now if it actually is the fastest. And if it were actually proven to be the fastest - that kind of "first position" is never held for long. And also "fastest" is not really a great focus to have just as "cheapest" when it comes to retail. Quality and flexibility is probably better to aim for.

**Comment by taojy123** [comment]
I agree with you. We can change the slogan.
