### ISSUE TITLE
Can not install valval using `v install`

### ISSUE THREAD

**Issue by shawnye** [taojy123/valval#2]
<pre>
C:\Users\Administrator>v install valval
Skipping module "valval", since it is missing name or url information.
</pre>

Please update it if it is convenient for you ,thank you !

**Comment by shawnye** [comment]
Sorry , I got it :
<pre>
v install watchmen123456.valval
</pre>

**Comment by taojy123** [comment]
try
```
v install watchmen123456.valval
```
Sorry for the wrong documention, I will correct it.
But I still recommend using the way of `git clone` to install

**Comment by adlesh** [comment]
Ah this was my bad sorry i messed up my merge and it reset that line. I'm sorry. There shouldn't be an issue using vpm though [just more to type]
