### ISSUE TITLE
Few ideas / suggestions

### ISSUE THREAD

**Issue by iredmail** [taojy123/valval#5]
- `register()` is used to register a route path, then why not make it clearer with `route()` directly?
- How about shorten `valval.Request` and `valval.Response` to `valval.Req`, `valval.Res`? Shorter, but still clear.
- Bound with Vue is cool, but will it limit valval to Vue users? How about people who don't use Vue at all? Python [Jinja2](https://jinja.palletsprojects.com/)-like template engine has high demand, it has clear syntax and powerful, easy to use.

**Comment by taojy123** [comment]
Thanks for your suggestions

- register => route is a good suggestion, I will add `route` function, but the `register` function is retained for compatibility.
- I originally wanted to add `Req` as a shorthand for `Request`, but I didn't find the way in v language.
- The real reason to use `vue` is ***write a template engine is so hard*** for static language like V 😄.

**Comment by taojy123** [comment]
Thanks for your suggestions

**Comment by iredmail** [comment]
Since V itself is not yet stable, I doubt anyone is using valval (except you) in production, so it’s quite safe to remove register and not consider backward compatibility. :)

Valval looks so simple compared to vweb and vex. You did a very great job. 

With Vue bond, you’re forcing people to learn Vue and that’s not good. :(

——
V 自身都还不稳定，没人用 V 更没人用 valval，所以不妨大刀阔斧地改一把，到后面再想改更不容易。

也许你顺便搞一个 jinja2 类似的模版系统？😂

**Comment by taojy123** [comment]
我其实主要是写 Python 的，去年一个偶然机会接触到了 V，其实也是玩票的心态。无论是 V 还是 valval 这玩意生产上是没法用的。
在 Python 里写一个模版引擎不是太难，但是对于写惯了 Python 的我，在这静态语言里写模版引擎还有 ORM 这些完整 web 框架必要的东西实在是太痛苦了，所以就放弃了。
我看了 vweb 里的模版是通过 $vweb.html() 这种编译时处理的方法来实现的，说实话没有太看明白，而且刚觉用起来也十分不方便。

目前比较明显的几个问题是：
- 没有 template 
- 没有 orm
- 单线程处理请求（这个要等官方做好 coroutine 功能）

**Comment by iredmail** [comment]
先完成上面几个 valval 的改进然后等 V 自己稳定先吧。

V 的作者没有进度规划，随口答应的事多了去了，不太靠谱，是否烂尾都不好说。

**Comment by taojy123** [comment]
哈哈 是的，之前说去年年底会出 0.2 的，现在没声音了 😂
